### ISSUE TITLE
Review code architecture

### ISSUE THREAD

**Issue by boyan-soubachov** [boyan-soubachov/tastyworks_api#5]
The current architecture is *very* MVP. I have done some basic work to refactor the different objects of interest (i.e. Orders, Trading accounts, etc.) into their own, class-based models but they all need to function off an underlying session (`TastyAPISession`).

My gut says we should use a factory method pattern here but we need to link the instances rather than the just the classes. 

Any thoughts and opinions would be appreciated.

**Comment by krsvojte** [comment]
Here are some points to think about:

One concern I see is that the tastyworks architecture is somewhat fragmented (combination of dxfeed, tastyworks api and dough), which we have to account for when receiving/sending data but otherwise we should develop our own abstract objects (such as the Order, Order Leg, etc.).  

Some of the objects shouldn't necessarily be tied to the session. For example, a useful thing would be a persistent storage of option/stock prices, volumes etc. for backtesting or just testing theoretical values. Therefore each object should be agnostic of where the data came from. As you mentioned, a factory pattern could be used, or an abstract "DataSource" class. Basically, a separation of server communication code and the object would be a good idea.

As far as I can tell, the only interaction in the direction of client to server will be sending orders. Everything else is just receiving and storing data. Therefore Order should be a special case and the order execution code could be in the session.

**Comment by boyan-soubachov** [comment]
Thank you for your input, @krsvojte 

```
One concern I see is that the tastyworks architecture is somewhat fragmented (combination of dxfeed, tastyworks api and dough), which we have to account for when receiving/sending data but otherwise we should develop our own abstract objects (such as the Order, Order Leg, etc.).
```

:100: . Busy with that as we speak.

```
Some of the objects shouldn't necessarily be tied to the session. For example, a useful thing would be a persistent storage of option/stock prices, volumes etc. for backtesting or just testing theoretical values. Therefore each object should be agnostic of where the data came from. As you mentioned, a factory pattern could be used, or an abstract "DataSource" class. Basically, a separation of server communication code and the object would be a good idea.
```

Very good point. My thought was to keep the same objects (i.e. Order, OptionsLeg, etc.) but make the tying to a trading session optional (pun slightly intended) so that one is able to create or get an `Order` or `OptionLeg` with and without a session. Thoughts or an alternative way?

```
As far as I can tell, the only interaction in the direction of client to server will be sending orders. Everything else is just receiving and storing data. Therefore Order should be a special case and the order execution code could be in the session.```

Good point, will have a look at this. :+1: 

Thanks again for the feedback. Wanted to also check if you'd be willing to be a collaborator on this (or whether you have the time at all)?

**Comment by krsvojte** [comment]
Object creation: well for now you could have a constructor for each object that is either called by the session with data taken from the server or with manually entered parameters. 

Collaboration: I'm willing to help here and there, but I cannot commit more than just a couple hours each week.

**Comment by boyan-soubachov** [comment]
Issue closed for now. Happy to review or adjust for any good feedback.
